import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/Navbar';
import { UserProvider } from '@/context/UserContext';
import RecommendedChannels from '@/components/RecommendedChannels';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <div className="flex min-h-screen">
            <div className="fixed top-0 left-0 w-full h-16 z-50 bg-gray-900">
              <Navbar />
            </div>

            <div className="hidden lg:block fixed top-16 left-0 w-64 h-full z-40 bg-gray-900">
              <RecommendedChannels />
            </div>

            <div className="lg:ml-64 flex-1">
              <div className="mt-16">{children}</div>
            </div>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
